# Generated by Django 4.2 on 2023-06-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpNo', models.IntegerField()),
                ('EmpName', models.CharField(max_length=20)),
                ('EmpSal', models.IntegerField()),
                ('empAddress', models.CharField(max_length=100)),
            ],
        ),
    ]
